"""Fix foreignkey issues

Revision ID: 9fe6a9bc1676
Revises: 8af59ebad87d
Create Date: 2025-02-19 13:50:54.144440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9fe6a9bc1676'
down_revision: Union[str, None] = '8af59ebad87d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('price_offset', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'ARCHIVED', name='productstatus'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_variant_sku'), 'product_variant', ['sku'], unique=True)
    op.drop_index('ix_productvariant_sku', table_name='productvariant')
    op.drop_table('productvariant')
    op.alter_column('orderitem', 'variant_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('orderitem_order_id_fkey', 'orderitem', type_='foreignkey')
    op.drop_constraint('orderitem_variant_id_fkey', 'orderitem', type_='foreignkey')
    op.create_foreign_key(None, 'orderitem', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orderitem', 'product_variant', ['variant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('payment', 'order_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index('ix_payment_order_id', table_name='payment')
    op.drop_constraint('payment_order_id_fkey', 'payment', type_='foreignkey')
    op.create_foreign_key(None, 'payment', 'order', ['order_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('productcategory_category_id_fkey', 'productcategory', type_='foreignkey')
    op.drop_constraint('productcategory_product_id_fkey', 'productcategory', type_='foreignkey')
    op.create_foreign_key(None, 'productcategory', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'productcategory', 'category', ['category_id'], ['id'], ondelete='CASCADE')
    op.alter_column('productimage', 'product_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('productimage_product_id_fkey', 'productimage', type_='foreignkey')
    op.create_foreign_key(None, 'productimage', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'productimage', type_='foreignkey')
    op.create_foreign_key('productimage_product_id_fkey', 'productimage', 'product', ['product_id'], ['id'])
    op.alter_column('productimage', 'product_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'productcategory', type_='foreignkey')
    op.drop_constraint(None, 'productcategory', type_='foreignkey')
    op.create_foreign_key('productcategory_product_id_fkey', 'productcategory', 'product', ['product_id'], ['id'])
    op.create_foreign_key('productcategory_category_id_fkey', 'productcategory', 'category', ['category_id'], ['id'])
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.create_foreign_key('payment_order_id_fkey', 'payment', 'order', ['order_id'], ['id'])
    op.create_index('ix_payment_order_id', 'payment', ['order_id'], unique=False)
    op.alter_column('payment', 'order_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.drop_constraint(None, 'orderitem', type_='foreignkey')
    op.create_foreign_key('orderitem_variant_id_fkey', 'orderitem', 'productvariant', ['variant_id'], ['id'])
    op.create_foreign_key('orderitem_order_id_fkey', 'orderitem', 'order', ['order_id'], ['id'])
    op.alter_column('orderitem', 'variant_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('productvariant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sku', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('price_offset', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('stock_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productvariant_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='productvariant_pkey')
    )
    op.create_index('ix_productvariant_sku', 'productvariant', ['sku'], unique=True)
    op.drop_index(op.f('ix_product_variant_sku'), table_name='product_variant')
    op.drop_table('product_variant')
    # ### end Alembic commands ###
